- hosts: webapps&:elasticseachs
  roles:
     - { role: ansiblebit.oracle-java, oracle_java_set_as_default: yes }

- hosts: elasticseachs
  roles:
     - { role: geerlingguy.elasticsearch}

- hosts: dbs
  roles:
     - { role: ANXS.postgresql}
  vars:
    postgresql_admin_user: "postgres"
    postgresql_default_auth_method: "md5"
    postgresql_databases:
      - name: myapp
    postgresql_users:
      - name: myappuser
        pass: myapppass
        encrypted: no 
    postgresql_user_privileges:
      - name: myappuser                   
        db: myapp                  
        priv: "ALL"              
        role_attr_flags: "CREATEDB" 
    postgresql_listen_addresses:
      - \*
    postgresql_pg_hba_default:
      - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: 'trust', comment: '' }
      - { type: local, database: all, user: all, address: '',             method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
      - { type: host,  database: all, user: all, address: '0.0.0.0/0', method: '{{ postgresql_default_auth_method }}', comment: 'IPv4 local connections:' }
      - { type: host,  database: all, user: all, address: '::1/128',      method: '{{ postgresql_default_auth_method }}', comment: 'IPv6 local connections:' }

- hosts: webapps
  roles:
     - { role: myapp}