Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty32"
    config.vm.hostname = "web1"
    config.vm.network "private_network", ip: "192.168.42.42"
    config.vm.provision "shell" do |s|
    	ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    	s.inline = <<-SHELL
      	echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      	echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    	SHELL
    end
end

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty32"
    config.vm.hostname = "web2"
    config.vm.network "private_network", ip: "192.168.42.43"
    config.vm.provision "shell" do |s|
    	ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    	s.inline = <<-SHELL
      	echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      	echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    	SHELL
    end
end